### ISSUE TITLE
ほこもくの進行の仕方を改善する

### ISSUE THREAD

**Issue by daiki-sato** [Daiki-Personal/posse_tech#10]
ほこもく司会がやること

(初回ほこもくのみ)
・スライドとスプシコピーを作り、ファイル名をいい感じの日付に変更する(ファイル内のいらないデータは削除する)
https://drive.google.com/drive/u/0/folders/196VJmer-iCWr_K1wT8dMMmAh5DDW-hYe

・不合格者を確認する(サンプリに回答結果のスプシを添付します)
https://docs.google.com/spreadsheets/d/1CQWlBKdKVeA4G1v_N9mm1Jo8QhIH9QJZZ6pB65TeMPY/edit#gid=540819286

こんな感じで共有↓
1.0, 1.5期生 全員合格:クラッカー:
2.0期生(不合格者)
14 / 30 松本透歩
16 / 30 山寺伶奈
2.5期生(不合格者)
12 / 30 葛西志保
17 / 30 遠藤愛期
17 / 30 布施　陸斗
12 / 30 早瀬凜太郎
14 / 30 五十嵐佳貴

ほこもく始める前に必要なページを開いておく(例として、ほこもく説明用スライド、分析スプシ、分析スライドを添付します)
https://docs.google.com/presentation/d/1nhmh5cJt9_4wWqtuYgFT9jusQbkkenNQuGOj6UDAoEA/edit#slide=id.ge30e78997b_0_5
https://docs.google.com/spreadsheets/d/1WgN_sz_vXyF_INiUxV1PLrI_Ji7pEExH1eB0MffQshY/edit#gid=0
https://docs.google.com/presentation/d/1OVImYNuURD99Fc0wopidiap_br03pF9AvYs3zRVpkMA/edit#slide=id.gf7ba4f3ad2_0_0

初回のみ : 1〜13ページ
通常：14〜22ページ

スライド通りに進行していただけたらOKです!
(実技テストの場合は少し時間が長かったりします)

初回ほこもくの録画
↓
https://drive.google.com/file/d/1A8q19CzBTOaWhpJ2-dvle5WD9HAYotlO/view?usp=sharing

**Comment by daiki-sato** [comment]
チェックテストのドライブに入ってるか確認

**Comment by tomoharuyuyama** [comment]
ほこもく司会がやること

0.
(初回ほこもくのみ)
・スライドとスプシコピーを作り、ファイル名をいい感じの日付に変更する(ファイル内のいらないデータは削除する)
https://drive.google.com/drive/u/0/folders/196VJmer-iCWr_K1wT8dMMmAh5DDW-hYe

・不合格者を確認する(サンプリに回答結果のスプシを添付します)
https://docs.google.com/spreadsheets/d/1CQWlBKdKVeA4G1v_N9mm1Jo8QhIH9QJZZ6pB65TeMPY/edit#gid=540819286

こんな感じで共有↓
1.0, 1.5期生 全員合格:クラッカー:
2.0期生(不合格者)
14 / 30	松本透歩
16 / 30	山寺伶奈
2.5期生(不合格者)
12 / 30	葛西志保
17 / 30	遠藤愛期
17 / 30	布施　陸斗
12 / 30	早瀬凜太郎
14 / 30	五十嵐佳貴


1.
ほこもく始める前に必要なページを開いておく(例として、ほこもく説明用スライド、分析スプシ、分析スライドを添付します)
https://docs.google.com/presentation/d/1nhmh5cJt9_4wWqtuYgFT9jusQbkkenNQuGOj6UDAoEA/edit#slide=id.ge30e78997b_0_5
https://docs.google.com/spreadsheets/d/1WgN_sz_vXyF_INiUxV1PLrI_Ji7pEExH1eB0MffQshY/edit#gid=0
https://docs.google.com/presentation/d/1OVImYNuURD99Fc0wopidiap_br03pF9AvYs3zRVpkMA/edit#slide=id.gf7ba4f3ad2_0_0

2.
初回のみ : 1〜13ページ
通常：14〜22ページ

スライド通りに進行していただけたらOKです!
(実技テストの場合は少し時間が長かったりします)

**Comment by daiki-sato** [comment]
あざ！！！！！ @tomoharuyuyama
