### ISSUE TITLE
講座スライドのリマインド・確認｜MUで講座・開催者を発表するので、月曜日までに

### ISSUE THREAD

**Issue by daiki-sato** [Daiki-Personal/posse_tech#20]
講座スライドを先輩に作成してもらう
### ・講座が被ってしまっているかの確認

**・スライド**

> https://docs.google.com/presentation/d/1f1uhseWBl9kv-SKhYmRd8qPCueGadnrSORnssIOwj5w/edit#slide=id.gfba759f9b2_0_5

・誰が参加したかチェックシート
> https://docs.google.com/spreadsheets/d/127nir7sQ7ORnjbo5q221R6-l3WoVpOcyRcJXKCGkXvo/edit#gid=0

**テンプレ**
```


<まだ作ってない人>
リマインドです課題サポート会の資料作りよろしくです！！
https://docs.google.com/presentation/d/1f1uhseWBl9kv-SKhYmRd8qPCueGadnrSORnssIOwj5w/edit#slide=id.gfc3726187c_0_15
一番最初だからもう当たり前！みたいなことを教えちゃっても全然可ですやってくれてありがとうよろしくです:おじぎ_女性:
<作り終わった人>
課題サポート会資料作りありがとう！
確認しましためっちゃいいですナイス！
当日よろしくねー！
```

**Comment by tomoharuyuyama** [comment]
・講座が被ってしまっているかの確認
→確認して、大きく内容がかぶっているところはなかったです。

**Comment by daiki-sato** [comment]
@tomoharuyuyama 
今週のスライド？

**Comment by tomoharuyuyama** [comment]
先週までのスライド全部

**Comment by daiki-sato** [comment]
今週のお願いします！
11/28の
