### ISSUE TITLE
課題サポート会のFBをLINEでもらって改善点考える

### ISSUE THREAD

**Issue by daiki-sato** [Daiki-Personal/posse_tech#32]
**FBもらうときのテンプレ**
```
先週は課題サポート会の講師ありがと!
よかったら、FB(3点, それ以外にあれば他にも)を頂きたいです

・全体的にどうだったか
・参加者のリアクション・どう教えたか
ex)quizyを見せながらとか
・依頼の仕方
ex)もう少し前に依頼された方が良かったか
　リマインド早くしてほしい
```

> 
> 
> 
> 
> [FB]
> ・全体的にどうだったか
> 全体的には、悪くなさそう。
> 他の人の教えてるところ見たけど、初日からマージンとかの話しても理解できないだろうから内容の精査はした方がよさそう。(シュート）
> 全体的に楽しかった！自分もいい復習になったし、2.5期とも仲良くなれて最高でした！(朝香)
> 
> 
> ・参加者のリアクション・どう教えたか
> リアクションは、ぼちぼち。どう教えたかは、私はいつも通り。ただ2.0期生は答え教えて気持ちよくなっていた印象(しゃーなし感)
> 参加者は説明は静かに聞いていて、その後私のコードを混ぜながらの解説になったらたくさん質問してくれました！(朝香)
> ・依頼の仕方
> ex)もう少し前に依頼された方が良かったか
> 　リマインド早くしてほしい
> 依頼のしかたは、いいのでは？
> ただ、講師によって当たり外れ(間違ったことを教える可能性)を減らすためにスライドはテック局が作ったもの＋αにしてみては？(シュート)
> 依頼はすごいスムーズで助かりました！(朝香)
> 
> 
> 
> メモ
> 
> かずきくん
> ・全体的にどうだったか
> →教える側も理解を深められるいい機会だった
> ・参加者のリアクション・どう教えたか
> →参加者のリアクションはとても良かった。教えたことを吸収するだけではなく、疑問にあったことなどを積極的に聞いてきてくれた。htmlタグを教えたが覚えてもらうというよりは使ってもらうことを重点において、具体例を使って使い方を説明した。
> ・依頼の仕方
> →スライド作成を金曜の12時までというアナウンスが木曜にあったのでもう少し早くアナウンスしてくれると良かった。

**Comment by daiki-sato** [comment]
■課題サポート会
１、課題サポート会のFBをLINEでもらって改善点考える
-講師-
[聞く人]

しゅーと
中澤和貴
朝香
ともくん
高梨彩音
朝香[2]



[聞く項目]
・全体的にどうだったか
・参加者のリアクション・どう教えたか
ex)quizyを見せながらとか
・依頼の仕方
ex)もう少し前に依頼された方が良かったか
　リマインド早くしてほしい

**Comment by tomoharuyuyama** [comment]
メモ

かずきくん
・全体的にどうだったか
→教える側も理解を深められるいい機会だった
・参加者のリアクション・どう教えたか
→参加者のリアクションはとても良かった。教えたことを吸収するだけではなく、疑問にあったことなどを積極的に聞いてきてくれた。htmlタグを教えたが覚えてもらうというよりは使ってもらうことを重点において、具体例を使って使い方を説明した。
・依頼の仕方
→スライド作成を金曜の12時までというアナウンスが木曜にあったのでもう少し早くアナウンスしてくれると良かった。
